verify checksum in build_fastly workflow

diff --git a/.github/workflows/build_fastly.yml b/.github/workflows/build_fastly.yml
--- a/.github/workflows/build_fastly.yml
+++ b/.github/workflows/build_fastly.yml
@@ -39,7 +39,11 @@ jobs:
           # TODO: find and parse latest version of Fastly CLI
           # This may be possible using the github REST API to list assets in a release
           # and fetching the one matching the fastly_<VERSION>_linux_amd64.deb pattern.
-          wget https://github.com/fastly/cli/releases/download/v11.2.0/fastly_11.2.0_linux_amd64.deb
+          wget -O fastly_11.2.0_linux_amd64.deb https://github.com/fastly/cli/releases/download/v11.2.0/fastly_11.2.0_linux_amd64.deb
+          if [ "$(sha256sum fastly_11.2.0_linux_amd64.deb | awk '{print $1}')" != "010cfbaf37ec02172b6485e327013757357a3cede2b30d5192f1eb90d44cad55" ]; then
+            echo "Checksum verification failed!"
+            exit 1
+          fi
           sudo dpkg -i fastly_11.2.0_linux_amd64.deb
           sudo apt-get update
           sudo apt-get install -y --fix-missing
